---
title: "Introduction to R"
author: "Clay Ford"
date: "Fall 2016"
output: beamer_presentation
---

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 50)
```

## Today's workshop

Teach you how to:

- read in and manipulate tabular data
- do some basic statistics
- do some graphing

I'm assuming you're new to R.  
\ 

The goal: get you comfortable enough to help yourself go further with R.


## Introducing R

- R is an environment for statistical computing and graphics that has a programming language
- Freely available and maintained by volunteers
- R is extensible; can be expanded by installing "packages" or by creating your own "functions"
- Frequently used with RStudio, a free IDE (Interactive Development Environment) for R


## How to get R and RStudio

**R**: http://cran.r-project.org/ (or better yet, Google "Download R")  
\ 

**RStudio**: http://www.rstudio.com/   
\ 

Both are available for Windows, Mac, and Linux and free to install (no catches).  
\ 

**After you install R and RStudio, you only need to run RStudio.**



## R basics - functions

* R uses *functions* to perform operations.

* Functions take *arguments* to specify how operations are performed. Example:

`read.csv(file="scores.csv")` 

* `read.csv` is a function to import a CSV file; `file` is an argument.

* R has **many** functions. Fortunately about 20% of them do about 80% of the work.


## R basics - running functions

Two common ways to run functions:

1. In the console at the command line; type the function and hit Enter
2. In an R script; type the function and (with cursor on same line as code) hit Ctrl + Enter (Win) or Command + Enter (Mac)

An R script is a text file that contains all your R code. R scripts allow you to save, edit, reproduce and share your code.   
\ 

Today's workshop will be centered around an R script I wrote in advance.



## R basics - assignment

* We often need to save a function's result or output. For this we use the assignment operator: ` <- `  

* For example, when you import a CSV file you need to give it a name: 

`scoreData <- read.csv(file="scores.csv")`   
 
* Now we can use `scoreData` as an argument to other functions. For example, computes summaries for each column in the data:

`summary(scoreData)` 

* **Note**: Use `Alt + -` (Win) or `Option + -` (Mac) in RStudio to quickly insert ` <- `. You can also use `=` for assignment.

## R basics - objects

- In R we create and manipulate *objects*. Examples of objects are vectors, matrices, data frames and lists. You can create as many objects as memory allows. 

- On the previous slide we created a data frame object called `scoreData`:

```
scoreData <- read.csv(file="scores.csv")
```


## R basics - packages

- All functions belong to *packages*. R comes with about 30 packages, but as of August 2016, there are *over 8700* user-contributed packages! 

- To use functions in a package, the package must be installed and loaded.

- You only _install_ a package once. 

- You _load_ a package whenever you want to use its functions. 

## R in a Nutshell

**Use functions in various packages to create and manipulate objects**.  
\ 

So we need to learn...

- some useful functions
- how to install and load packages
- about different R objects
- how to use RStudio
- how to get help

Let's open up RStudio and get started!


## Keep Going!

- Join the UVa R Users Group: http://www.meetup.com/UVa-R-Users-Group/

- Sign up for the R-Bloggers daily email: http://www.r-bloggers.com/

- Lander, J., *R for Everyone*, Addison-Wesley, 2014.

- Teetor, P., *R Cookbook*, O'Reilly, 2011.

- Hothorn, T. & Everitt, B., *A Handbook of Statistical Analyses Using R*, CRC Press, 2009.

## Check out these web sites

- Contributed Documentation: http://cran.r-project.org/other-docs.html

- Quick-R: http://www.statmethods.net/

- Cookbook for R: http://www.cookbook-r.com/

- R-statistics blog: http://www.r-statistics.com/

- The R Journal: http://journal.r-project.org/

- UCLA R Starter Kit: http://www.ats.ucla.edu/stat/r/sk/


## StatLab

Thanks for coming today!  
\ 

For help and advice with your data analysis, contact us: statlab@virginia.edu  
\ 

Sign up for more workshops or see past workshops:
http://data.library.virginia.edu/training/   
\ 

Register for the Research Data Services newsletter to be notified of future workshops: http://data.library.virginia.edu/newsletters/
